/**
 * Returns Module Entry Point
 * จุดเข้าใช้งานสำหรับ returns module
 */

// Export ค่าคงที่และ schema
export {
  RETURN_TYPES,
  RETURN_STATUS,
  RETURN_REASONS,
  RETURN_CONDITIONS,
  RETURN_ACTIONS,
  COMPENSATION_TYPES,
  PRIORITY_LEVELS,
  INSPECTION_RESULTS,
  RETURN_CHANNELS,
  COST_TYPES,
  REFUND_STATUS,
  REFUND_METHODS,
  RETURN_TYPE_LABELS,
  RETURN_STATUS_LABELS,
  RETURN_REASON_LABELS,
  RETURN_CONDITION_LABELS,
  RETURN_ACTION_LABELS,
  COMPENSATION_TYPE_LABELS,
  PRIORITY_LEVEL_LABELS,
  INSPECTION_RESULT_LABELS,
  RETURN_CHANNEL_LABELS,
  COST_TYPE_LABELS,
  REFUND_STATUS_LABELS,
  REFUND_METHOD_LABELS,
  RETURN_CONFIG,
  RETURN_DEFAULTS,
  RETURN_TEMPLATES
} from './schema.js'

// Export ข้อมูลและฟังก์ชัน
export {
  RETURNS_CODE_CONFIG,
  ReturnsMasterData,
  ReturnsUtils
} from './data.js'

// Export default
export { default } from './data.js'