/**
 * Delivery Module Entry Point
 * จุดเข้าใช้งานสำหรับ delivery module
 */

// Export ค่าคงที่และ schema
export {
  DELIVERY_TYPES,
  DELIVERY_STATUS,
  SHIPPING_METHODS,
  VEHICLE_TYPES,
  PRIORITY_LEVELS,
  DELIVERY_ZONES,
  FAILURE_REASONS,
  PACKAGING_TYPES,
  INSURANCE_TYPES,
  DELIVERY_TERMS,
  TIME_SLOTS,
  DELIVERY_TYPE_LABELS,
  DELIVERY_STATUS_LABELS,
  SHIPPING_METHOD_LABELS,
  VEHICLE_TYPE_LABELS,
  PRIORITY_LEVEL_LABELS,
  DELIVERY_ZONE_LABELS,
  FAILURE_REASON_LABELS,
  TIME_SLOT_LABELS,
  DELIVERY_CONFIG,
  DELIVERY_DEFAULTS,
  DELIVERY_STATES,
  DELIVERY_TRANSITIONS,
  DELIVERY_INITIAL_STATE,
  DELIVERY_STORAGE_KEY,
  DELIVERY_FIELD_SCHEMA
} from './schema.js'

// Export ข้อมูลและฟังก์ชัน
export {
  DELIVERY_CODE_CONFIG,
  DeliveryMasterData,
  DeliveryUtils
} from './data.js'

// Export default
export { default } from './data.js'