/**
 * Production Module Entry Point
 * จุดเข้าใช้งานสำหรับ production module
 */

// Export ค่าคงที่และ schema
export {
  PRODUCTION_TYPES,
  PRODUCTION_STATUS,
  PRODUCTION_ORDER_STATUS,
  PROCESS_TYPES,
  PROCESS_STATUS,
  PRIORITY_LEVELS,
  SCRAP_TYPES,
  QUALITY_CHECK_TYPES,
  QUALITY_RESULTS,
  MACHINE_TYPES,
  MACHINE_STATUS,
  DOWNTIME_TYPES,
  PRODUCTION_UNITS,
  COSTING_METHODS,
  PRODUCTION_TYPE_LABELS,
  PRODUCTION_STATUS_LABELS,
  PRODUCTION_ORDER_STATUS_LABELS,
  PROCESS_TYPE_LABELS,
  PROCESS_STATUS_LABELS,
  PRIORITY_LEVEL_LABELS,
  SCRAP_TYPE_LABELS,
  QUALITY_CHECK_TYPE_LABELS,
  QUALITY_RESULT_LABELS,
  MACHINE_TYPE_LABELS,
  MACHINE_STATUS_LABELS,
  DOWNTIME_TYPE_LABELS,
  PRODUCTION_UNIT_LABELS,
  COSTING_METHOD_LABELS,
  PRODUCTION_CONFIG,
  PRODUCTION_DEFAULTS,
  PRODUCTION_TEMPLATES
} from './schema.js'

// Export ข้อมูลและฟังก์ชัน
export {
  PRODUCTION_CODE_CONFIG,
  ProductionMasterData,
  ProductionUtils
} from './data.js'

// Export default
export { default } from './data.js'